### ISSUE TITLE
Remove self.kwargs from the trainer

### ISSUE THREAD

**Issue by wuhu** [blythed/torchabc#3]
One should not assume that kwargs contains anything.
A suggestion would be to create an 'Options'-class for all the fixed parameters (such as 'batch_size', 'num_workers'... maybe use the new dataclass for that https://www.python.org/dev/peps/pep-0557/, although it's not supported before python 3.7). Other things (callback, writer) could just be handled as explicit keyword arguments.

**Comment by blythed** [comment]
Resolved in latest merge.
